name: GAD2020
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  url_launcher: ^5.7.10

dev_dependencies:
  pedantic: ^1.9.2
  audioplayers: 0.17.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Buna ziua.mp3
    - assets/Ce mai faceti.mp3
    - assets/Ciao.mp3
    - assets/Cosa stai facendo.mp3
    - assets/Dove si trova la stazione ferroviaria.mp3
    - assets/Unde este gara.mp3
    - assets/Vrei sa bei bere.mp3
    - assets/Vuoi bere birra.mp3